## <div align="center"> Homework 2</div>
## <div align="center"> Network Analytics</div>
### <div align="center"> Group Assignment</div>
### <div align="center"> Question 3</div>

<br><div align="center"> By Group A3: </div>
<div align="center"> Jiaqi Chen, Yuxi Fu, Jiaxuan Lyu, Maria Tsotalou, Qian Zhang </div>


### a) 

We formulate the problem of sending the maximum amount of flow from Node 1 to
Node 5 in the  network as a linear program

Let the flow that enters the node 1 and exits node 5 be f.

The linear optimisation problem is formulated as follows

__Objective function:__
maximize(f)

__Variables:__
<br>$f$: that enters the exit 1 and exits node 5
<br>$x_{12}$: flow from node 1 to node 2 
<br>$x_{13}$: flow from node 1 to node 3 
<br>$x_{14}$: flow from node 1 to node 4 
<br>similiralily we define $x_{24}, x_{25}, x_{35}, x_{43}, x_{45}$


__Constraints:__

Flow conservation:
<br> $node_1: - x_{12} - x_{13} - x_{14}  + f      = 0$
<br> $node_2: + x_{12} - x_{24} - x_{25}          = 0$
<br> $node_3: + x_{13} + x_{43} - x_{35}          = 0$
<br> $node_4: + x_{14} + x_{24} - x_{43} - x_{45} = 0$
<br> $node_5: + x_{25} + x_{35} + x_{45} - f      = 0$

Capacity:
<br>$x_{12} <=5$
<br>$x_{13} <=2$
<br>$x_{14} <=1$
<br>$x_{24} <=3$
<br>$x_{25} <=1$
<br>$x_{35} <=7$
<br>$x_{43} <=1$
<br>$x_{45} <=4$

Non-negativity:
<br>All $x_{i} >= 0, \ f >= 0$

### b)

Let the above problem be resembled as:

<br>__Objective function:__ 
<br> $maximise (c^T*x)$
<br> where $c = [0, 0, 0, 0, 0, 0, 0, 0, 1]$

<br>__Variables:__ 
<br>$x = [x_{12}, x_{13}, x_{14}, x_{24}, x_{25}, x_{35}, x_{43}, x_{45}]^T$

__Constraints:__
<br>$Ax<=b$
<br> Where,
$b = [0, 0, 0, 0, 0, 5, 2, 1, 3, 1, 7, 1, 4] ^T$ 
(actually the first five rows are of the format Ax = b )
and 

In [1]:
import numpy as np
            
A = np.matrix('-1 -1 -1 0 0 0 0 0 1; 1 0 0 -1 -1 0 0 0  0; \
0 1  0 0 0 -1 1 0 0 ; 0 0 1 1 0 0 -1 -1 0; 0 0 0 0 1 1 0 1 -1; \
1 0 0 0 0 0 0 0 0; 0 1 0 0 0 0 0 0 0; 0 0 1 0 0 0 0 0 0;\
0 0 0 1 0 0 0 0 0; 0 0 0 0 1 0 0 0 0; 0 0 0 0 0 1 0 0 0; \
0 0 0 0 0 0 1 0 0; 0 0 0 0 0 0 0 1 0')
print("A = ")
print(A)

A = 
[[-1 -1 -1  0  0  0  0  0  1]
 [ 1  0  0 -1 -1  0  0  0  0]
 [ 0  1  0  0  0 -1  1  0  0]
 [ 0  0  1  1  0  0 -1 -1  0]
 [ 0  0  0  0  1  1  0  1 -1]
 [ 1  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  1  0]]


From optimisation theory we know that the dual problem will be of the form:

<br>__Objective function:__ 
<br> $minimize (b^T*y)$

<br>__Variables:__ 
<br>$y = [y_{1}, _{2}, y_{3}, y_{4}, y_{5}, y_{6}, y_{7}, y_{8},  y_{9},  y_{10},  y_{11}, y_{12},  y_{13}]^T$

__Constraints:__
<br>$A^T*y<=b$
<br> 

In [2]:
At = A.transpose()
print("transpose A =")
print(At)

transpose A =
[[-1  1  0  0  0  1  0  0  0  0  0  0  0]
 [-1  0  1  0  0  0  1  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0  1  0  0  0  0  0]
 [ 0 -1  0  1  0  0  0  0  1  0  0  0  0]
 [ 0 -1  0  0  1  0  0  0  0  1  0  0  0]
 [ 0  0 -1  0  1  0  0  0  0  0  1  0  0]
 [ 0  0  1 -1  0  0  0  0  0  0  0  1  0]
 [ 0  0  0 -1  1  0  0  0  0  0  0  0  1]
 [ 1  0  0  0 -1  0  0  0  0  0  0  0  0]]


We will use Excel solver to solve the problem. 

The dual problem in excel is solved as following:

![title](images/Q3_excel_sheet_dual.png)

While the sensitivity analysis leads to 

![title](images/Q3_excel_sheet_dual_sensitivity.png)

It is worth noticing that essentialy we could solve only the primal problem since from the sensitivity analysis (from the shadow rices actually) of the primal problem we can find the optimal solution of the dual one and vice versa. This becomaes obvious from the sensitivity analysis of the primal problem. 



The primal  problem in excel is solved as following:

![title](images/Q3_excel_sheet_primal.png)

While the sensitivity analysis of the primal leads to 

![title](images/Q3_excel_sheet_primal_sensitivity.png)

### c)

A min-cut is a cut with the minimum capacity, where capacity of the cut Cap(S, T) = sum of the capacities of edges from S to T.

It is reasonable that the max-flow <= min-cut capacity as this minimum capacity poses essentialy a bottleneck to the system. In order to understand this fully we will depict it with an example. 

We now that for the capacity: $cap_{S,T} = sum (capacities\ of \ edges\ from\ S\ to\ T)$

<br> While for the flow: $flow_{cut} = flow_{out} - flow_{in}$
<br> however,  $flow_{out} <= cap_{cut}$ 
<br> thus for each cut $ flow_{cut} <=  cap_{cut}$


Any given cut divides the network into two subsets. The flow at a given point can be depicted as the flow between these two subsets. The maximum flow for the total network is equal to the flow of the cut with the smallest maximum flow which, as it is concluded from the above inequality, is the cut with the minimum capacity. 

### d)

.We know that the shadow price of a constraint gives us the change of the optimal objective funcction value if the right hand side of the constraint is increased by one unit value. The shadow prices can give us an indication of which constraints are binding for the optimisation problem. 
The sensitivity analysis of the prmal problem, which we have depicted in question b too, is the following.

![title](images/Q3_excel_sheet_primal_sensitivity_annotation.png)

It becomes apparent that the capacity of the edges 2-5, 2-4, 1-4, and 1-3 are binding for our problem since they have non-zero shadow prices. 

If we observe our network these edges correspond to the following cut

![title](images/network_cut.png)

That gives us the minimum capacity cut for our network.